# Sales Data ETL Pipeline

## Project Overview

This project demonstrates a simple ETL (Extract, Transform, Load) pipeline using Python, Pandas, and SQLite.

### Technologies Used
- Python
- Pandas
- NumPy
- SQLite
- SQL

## ETL Process

### Extract
Created and loaded sales data into a Pandas DataFrame.

### Transform
- Checked for missing values
- Calculated total sales
- Standardized column names

### Load
Loaded the transformed data into a SQLite database.

## SQL Analysis
- Calculated total revenue
- Analyzed sales by product
- Identified product-wise revenue and quantity sold

In [1]:
import pandas as pd
import numpy as np

# Create sample sales data
data = {
    "Order_ID": range(1001, 1021),
    "Customer": [
        "Rahul", "Priya", "Amit", "Sneha", "Kiran",
        "Anjali", "Ravi", "Divya", "Arjun", "Neha",
        "Vikram", "Pooja", "Suresh", "Meena", "Akash",
        "Kavya", "Rohan", "Swathi", "Manoj", "Deepa"
    ],
    "Product": [
        "Laptop", "Phone", "Headphones", "Laptop", "Phone",
        "Headphones", "Laptop", "Phone", "Headphones", "Laptop",
        "Phone", "Laptop", "Headphones", "Phone", "Laptop",
        "Headphones", "Phone", "Laptop", "Phone", "Headphones"
    ],
    "Quantity": [
        1, 2, 1, 1, 3,
        2, 1, 2, 3, 1,
        1, 2, 2, 3, 1,
        1, 2, 1, 3, 2
    ],
    "Price": [
        70000, 25000, 3000, 72000, 24000,
        3500, 68000, 26000, 2800, 71000,
        23000, 69000, 3200, 27000, 73000,
        3300, 25500, 70000, 24500, 3100
    ]
}

df = pd.DataFrame(data)

# Show the dataset
df.head()

   Order_ID Customer     Product  Quantity  Price
0      1001    Rahul      Laptop         1  70000
1      1002    Priya       Phone         2  25000
2      1003     Amit  Headphones         1   3000
3      1004    Sneha      Laptop         1  72000
4      1005    Kiran       Phone         3  24000

In [9]:
# Check for missing values
print("Missing values:")
print(df.isnull().sum())

# Create a new column: Total_Sales
df["total_sales"] = df["quantity"] * df["price"]

# Convert column names to lowercase
df.columns = df.columns.str.lower()

# Display the updated dataset
df.head()

Missing values:
order_id       0
customer       0
product        0
quantity       0
price          0
total_sales    0
dtype: int64

   order_id customer     product  quantity  price  total_sales
0      1001    Rahul      Laptop         1  70000        70000
1      1002    Priya       Phone         2  25000        50000
2      1003     Amit  Headphones         1   3000         3000
3      1004    Sneha      Laptop         1  72000        72000
4      1005    Kiran       Phone         3  24000        72000

In [10]:
import sqlite3

# Create a connection to a SQLite database
conn = sqlite3.connect("sales.db")

# Load the DataFrame into a SQL table
df.to_sql(
    "sales",
    conn,
    if_exists="replace",
    index=False
)

print("Data successfully loaded into SQL database!")

Data successfully loaded into SQL database!

In [11]:
# Read all data from the sales table
query = "SELECT * FROM sales"

result = pd.read_sql_query(query, conn)

result.head()

   order_id customer     product  quantity  price  total_sales
0      1001    Rahul      Laptop         1  70000        70000
1      1002    Priya       Phone         2  25000        50000
2      1003     Amit  Headphones         1   3000         3000
3      1004    Sneha      Laptop         1  72000        72000
4      1005    Kiran       Phone         3  24000        72000

In [14]:
# Total Revenue
query = """
SELECT
    SUM(total_sales) AS total_revenue
FROM sales;
"""

total_revenue = pd.read_sql_query(query, conn)

total_revenue

   total_revenue
0         998800

In [15]:
query = """
SELECT
    product,
    SUM(quantity) AS total_quantity_sold,
    SUM(total_sales) AS total_revenue
FROM sales
GROUP BY product
ORDER BY total_revenue DESC;
"""

product_sales = pd.read_sql_query(query, conn)

product_sales

      product  total_quantity_sold  total_revenue
0      Laptop                    8         562000
1       Phone                   16         402500
2  Headphones                   11          34300